//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HerramientaCartera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HerramientaCartera()
        {
            this.Factura = new HashSet<Factura>();
            this.Letra = new HashSet<Letra>();
            this.RecibosxHonorario = new HashSet<RecibosxHonorario>();
        }
    
        public int IdHerramientaCartera { get; set; }
        public Nullable<System.DateTime> fechaInicial { get; set; }
        public Nullable<System.DateTime> fechaFinal { get; set; }
        public Nullable<double> ValorNominal { get; set; }
        public Nullable<double> retencion { get; set; }
        public Nullable<double> ValorExpresadoCGI { get; set; }
        public Nullable<double> ValorExpresadoCGF { get; set; }
        public string TipoMoneda { get; set; }
        public string PlazoTasa { get; set; }
        public Nullable<double> TasaEoN { get; set; }
        public Nullable<System.DateTime> FechaDescuento { get; set; }
        public string TipoTasa { get; set; }
        public Nullable<double> TEporcentaje { get; set; }
        public Nullable<double> dporcentaje { get; set; }
        public Nullable<double> descuento { get; set; }
        public Nullable<double> valorNeto { get; set; }
        public Nullable<double> valorTotalaRecibir { get; set; }
        public Nullable<double> valorTotalaEntregar { get; set; }
        public Nullable<double> TCEA { get; set; }
        public Nullable<int> dias { get; set; }
        public Nullable<double> MonedaSoles { get; set; }
        public Nullable<double> MonedaDolares { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Letra> Letra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecibosxHonorario> RecibosxHonorario { get; set; }
    }
}
